### ISSUE TITLE
[BUG] Constraint/Formula Windows opens in full screen

### ISSUE THREAD

**Issue by rickyphewitt** [linuxserver/docker-freecad#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking add constraint or formula button to input a value referenced from a spreadsheet the window opens full screen obscuring anything behind it.

![FullScreenConstraintWindow](https://github.com/user-attachments/assets/c2da28ed-65ad-43fe-866c-5f0d8907b0fa)
 

### Expected Behavior

In my local freecad instance the formula window opens in a more compact way still allowing view of the main workspace. 

![CorrectSizeConstraintWindow](https://github.com/user-attachments/assets/e7103c61-f80b-4250-9d9b-1d157ac996a3)

### Steps To Reproduce

1. Using FreeCAD 0.20.0 release
2. File -> New 
3. Set the workspace to Part Design
4. Use the Tasks tab then click Create Body
5. Then from the Tasks tab click Create Sketch, Choose your Plane
6. From the Sketcher Workspace draw a line
7. Click on the Line and Apply a Constraint
8. Constraint Window is Full Screen (should not be full screen)
9. Click on the Formula Icon in the upper right
10. Formula Window is Full screen (should not be full screen)

You can manually minimize it and the window is the correct size. Same as a my local install of FreeCad. 

### Environment

```markdown
- OS:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

- How docker service was installed:
Ubuntu Package Manager
```

### CPU architecture

x86-64

### Docker creation

```bash
version: '3.1'
services:
  freecad:
    image: lscr.io/linuxserver/freecad:latest
    container_name: freecad
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=33
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3004:3000
      - 3005:3001
    restart: unless-stopped


excluded volume mounts as those are specific to my impl
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    33
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.2.0 - built Jun 15 2024 18:56:53
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Obt-Message: Xinerama extension is not present on the server
[ls.io-init] done.
Traceback (most recent call last):
  File "<string>", line 8, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lsiopy/bin/activate_this.py'
Failed to create /var/www/.cache for shader cache (Permission denied)---disabling.
FreeCAD 0.20.2, Libs: 0.20.2R
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##
```

**Comment by aptalca** [comment]
`NO_FULL`
https://github.com/linuxserver/docker-freecad?tab=readme-ov-file#optional-environment-variables

**Comment by rickyphewitt** [comment]
Aaand that worked. Thank you!!
